/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import co.edu.eam.disenosoft.universidad.logica.Excepcion.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.RegistroCurso;
import co.edu.eam.disenosoft.universidad.modelo.SesionCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorVerRegistroEstudiante;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dir_software
 */
public class VentanaVerRegistroEstudiante extends javax.swing.JInternalFrame {
    ControladorVerRegistroEstudiante controlador;
    /**
     * Creates new form VentanaRegistrarCurso
     */
    public VentanaVerRegistroEstudiante() {
        initComponents();
         setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);       
        setClosable(true);
        controlador= new ControladorVerRegistroEstudiante();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHorario = new javax.swing.JTable();
        btnQuitarAsignatura = new javax.swing.JButton();
        tfCodigoCurso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfcedulaestudiante = new javax.swing.JTextField();
        btnBuscarEstuainte = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombreestudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcreditosregistradosestudiante = new javax.swing.JTextField();

        setIconifiable(true);
        setTitle("Ver Registro Estudiante");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursos Registrados"));

        jScrollPane1.setBorder(null);

        tablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Asignatura", "Horario"
            }
        ));
        jScrollPane1.setViewportView(tablaHorario);

        btnQuitarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
        btnQuitarAsignatura.setToolTipText("Quitar Asignatura Registrada");
        btnQuitarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAsignaturaActionPerformed(evt);
            }
        });

        tfCodigoCurso.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuitarAsignatura)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(tfCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnQuitarAsignatura))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(tfCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Estudiante"));

        jLabel3.setText("Cedula");

        btnBuscarEstuainte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarEstuainte.setToolTipText("Buscar Docente");
        btnBuscarEstuainte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstuainteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombreestudiante.setEditable(false);

        jLabel6.setText("Creditos Registrados");

        tfcreditosregistradosestudiante.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcedulaestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(tfnombreestudiante)
                    .addComponent(tfcreditosregistradosestudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarEstuainte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfcedulaestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfnombreestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcreditosregistradosestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEstuainteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstuainteActionPerformed
        // TODO add your handling code here:
        try{
            if(tfcedulaestudiante.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese la cedula dele estudiante");
            }else{
                Estudiante estudiante= controlador.buscar(tfcedulaestudiante.getText());
                if(estudiante==null){
                    JOptionPane.showMessageDialog(null, "No hay un estudiante registrado con esta cedula");
                }else{
                    tfnombreestudiante.setText(estudiante.getNombre());
                    tfcreditosregistradosestudiante.setText(controlador.creditosRegistradoEstu(estudiante)+"");
                    List<RegistroCurso> listaCursos= controlador.listarCursosDelEstudinte(estudiante);
                    CargarTabla(listaCursos);
                   
                                    
                    
                }
            }
        }catch(Exception e1){
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarEstuainteActionPerformed

    private void btnQuitarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAsignaturaActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
            if (tabla.getRowCount() != 0) {
                int c = tablaHorario.getSelectedRow();
                if (c > -1) {
                    String cods = tfCodigoCurso.getText();
                    String[] codCursos = cods.split(",");
                    String codigo = codCursos[c + 1];
                    Estudiante estudiante = controlador.buscar(tfcedulaestudiante.getText());
                    Curso curso = controlador.buscarCurso(codigo);
                    RegistroCurso rc = controlador.buscarRegCur(curso, estudiante);
                    controlador.eliminar(rc);
                    JOptionPane.showMessageDialog(null, "El curso ah sido "
                            + "eliminado exitosamente");
                    List<RegistroCurso> listaRegCur = controlador.listarCursosDelEstudinte(estudiante);
                    CargarTabla(listaRegCur);
                } else {
                    JOptionPane.showMessageDialog(null, "Elija un curso de la tabla");
                }
            }
        }catch(ExcepcionNegocio ex){
    		JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnQuitarAsignaturaActionPerformed
    
    public void CargarTabla(List<RegistroCurso> lista) {
        DefaultTableModel tabla = (DefaultTableModel) tablaHorario.getModel();
        List<SesionCurso> sesiones = new ArrayList();
        tabla.setRowCount(0);
        String codigo = "";
        for (RegistroCurso registroCurso : lista) {
            String horario = "";
            sesiones = registroCurso.getCurso().getSesiones();
            for (SesionCurso sesionCu : sesiones) {
                horario += " " + sesionCu.getDia().toString() + ":"
                        + sesionCu.getHoraInicio() + "-"
                        + sesionCu.getHoraFinal();

            }
            tabla.addRow(new Object[]{registroCurso.getCurso()
                .getAsignatura().getNombre(), horario});
            codigo = codigo + "," + registroCurso.getCurso().getCodigo();
            tfCodigoCurso.setText(codigo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstuainte;
    private javax.swing.JButton btnQuitarAsignatura;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHorario;
    private javax.swing.JTextField tfCodigoCurso;
    private javax.swing.JTextField tfcedulaestudiante;
    private javax.swing.JTextField tfcreditosregistradosestudiante;
    private javax.swing.JTextField tfnombreestudiante;
    // End of variables declaration//GEN-END:variables
}
