/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import co.edu.eam.disenosoft.universidad.modelo.Asignatura;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.RegistroCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorVentanaCrearCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorVentanaVerCurso;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dir_software
 */
public class VentanaVerCurso extends javax.swing.JInternalFrame {

    private ControladorVentanaVerCurso controlador;

    /**
     * Creates new form VentanaVerCurso
     */
    public VentanaVerCurso() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);
        setClosable(true);
        controlador = new ControladorVentanaVerCurso();
    }
    
    public int calculoEdad(Estudiante estudiante){
        int edad=0;
        int anio= estudiante.getFechaNacimiento().getYear()+1900;
        int mes= estudiante.getFechaNacimiento().getMonth();
        int dia= estudiante.getFechaNacimiento().getDate();
        Calendar fecha= new GregorianCalendar();
        int anioActual= fecha.get(Calendar.YEAR);
        int mesActual= fecha.get(Calendar.MONTH);
        int diaActual= fecha.get(Calendar.DAY_OF_MONTH);
        int  anioo= anioActual-anio;
        int mess= mesActual-mes;
        int diaa= diaActual- dia;
        if(mess<0 || (mes==0 && diaa<0)){
            edad= anioo-1;
        }else{
            edad=anioo*-1;
        }
        return edad;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboCursos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnVerEstudiante = new javax.swing.JButton();

        setTitle("Ver Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        jLabel3.setText("Curso");

        comboCursos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnombreasignatura)
                            .addComponent(comboCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/classroom.png"))); // NOI18N

        btnVerEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student6.png"))); // NOI18N
        btnVerEstudiante.setToolTipText("Ver Estudiante");
        btnVerEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1))
                    .addComponent(btnVerEstudiante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerEstudiante)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstudianteActionPerformed
        // TODO add your handling code here:
        
        try{
            Curso curso= controlador.buscarCurso((String) comboCursos.getSelectedItem());
            if(curso!=null){
                DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
                int c = jTable1.getSelectedRow();
                if (c > -1) {
                    String cedEst = (String) tabla.getValueAt(c, 0);
                    Estudiante estudiante = controlador.buscarEstudiante(cedEst);
                    List<Long>  creditos = controlador.creditosEstudiante(estudiante);
                    DialogoVerEstudiante dialogo = new DialogoVerEstudiante(estudiante, curso,
                            controlador);
                
            }
            }
        }catch(Exception e1){
            e1.printStackTrace();
        }
       
    }//GEN-LAST:event_btnVerEstudianteActionPerformed

    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
        // TODO add your handling code here:
        try {
            if (tfcodigoasignatura.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Porfavor digitar el código de "
                        + "la asignatura");
            } else {
                Asignatura asignatura = controlador.buscarAsignatura(tfcodigoasignatura.getText());
                if (asignatura == null) {
                    JOptionPane.showMessageDialog(null, "No se encontro ninguna "
                            + "asignatura");

                } else {
                    tfnombreasignatura.setText(asignatura.getNombre());
                    List<Curso> cursoo;
                    cursoo = controlador.listarCursosPorAsignatura(asignatura);
                    if (cursoo == null) {
                        JOptionPane.showMessageDialog(null, "La asignatura no tiene cursos");
                    } else {
                    	cargarComboCursos(cursoo);
                    }
                }
            }
        } catch (Exception e1) {
            e1.printStackTrace();

        }

    }//GEN-LAST:event_btnBuscarAsignaturaActionPerformed

    private void comboCursosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCursosItemStateChanged
        // TODO add your handling code here:
        try{
            DefaultTableModel tab= (DefaultTableModel) jTable1.getModel();
            if(comboCursos.getSelectedIndex()!=0){
                String codigoCurso=(String) comboCursos.getSelectedItem();
                if(codigoCurso==null){
                    return;
                }
                
                Curso curso= controlador.buscarCurso(codigoCurso);
                List<RegistroCurso> lista= controlador.listartodoslosregistrodecursoEstu(curso);
                tab.setRowCount(0);
                if(lista !=null){
                    for(RegistroCurso rC: lista){
                        Estudiante estu= rC.getEstudiante();
                        int edad= calculoEdad(estu);
                        tab.addRow(new Object[]{estu.getCedula(), estu.getNombre(), estu.getApellido(),edad});
                    }
                }
            }
           
        }catch (Exception exc) {
            
            exc.printStackTrace();
        }
    }//GEN-LAST:event_comboCursosItemStateChanged

    public void cargarComboCursos(List<Curso> cursos) {
        comboCursos.removeAllItems();
        comboCursos.addItem("Seleccione un curso");
        for (int i = 0; i < cursos.size(); i++) {
            comboCursos.addItem(cursos.get(i).getCodigo());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnVerEstudiante;
    private javax.swing.JComboBox comboCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    // End of variables declaration//GEN-END:variables
}
