/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.disenosoft.universidad.vista.gui;

import co.edu.eam.disenosoft.universidad.logica.Excepcion.ExcepcionNegocio;
import co.edu.eam.disenosoft.universidad.modelo.Curso;
import co.edu.eam.disenosoft.universidad.modelo.Docente;
import co.edu.eam.disenosoft.universidad.modelo.Estudiante;
import co.edu.eam.disenosoft.universidad.modelo.Evaluacion;
import co.edu.eam.disenosoft.universidad.modelo.Nota;
import co.edu.eam.disenosoft.universidad.modelo.RegistroCurso;
import co.edu.eam.disenosoft.universidad.vista.controlador.ControladorVentanaIngresarCalificaciones;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dir_software
 */
public class VentanaIngresarCalificaciones extends javax.swing.JInternalFrame {

    private ControladorVentanaIngresarCalificaciones controlador;
    private Docente docente;
    private Curso curso;

    /**
     * Creates new form VentanaIngresarCalificaciones
     */
    public VentanaIngresarCalificaciones() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);
        controlador = new ControladorVentanaIngresarCalificaciones();
        docente = null;
        curso = null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfceduladocente = new javax.swing.JTextField();
        btnBuscarAsignatura1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfnombredocente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        comboCurso = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combocalificacion = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalificaicon = new javax.swing.JTable();
        btnCalificar = new javax.swing.JButton();

        setTitle("Ingresar Calificaiones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Docente"));

        jLabel3.setText("Cedula");

        btnBuscarAsignatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura1.setToolTipText("Buscar Docente");
        btnBuscarAsignatura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignatura1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        tfnombredocente.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfceduladocente, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(tfnombredocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarAsignatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscarAsignatura1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfceduladocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombredocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(5, 5, 5))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones"));

        comboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursoItemStateChanged(evt);
            }
        });

        jLabel5.setText("Curso");

        jLabel6.setText("Calificacion");

        combocalificacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocalificacionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCurso, 0, 240, Short.MAX_VALUE)
                    .addComponent(combocalificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combocalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check44.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Estudiantes"));

        tablaCalificaicon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(tablaCalificaicon);

        btnCalificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pen41.png"))); // NOI18N
        btnCalificar.setToolTipText("Calificar Estudiante Seleccionado de la Tabla");
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalificar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAsignatura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignatura1ActionPerformed
        // TODO add your handling code here:
        try {
            if (tfceduladocente.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor ingresar el la "
                        + "cedula del docente que desea buscar");
            } else {
                String codigo = tfceduladocente.getText();
                docente = controlador.buscDocente(codigo);
                if (docente == null) {
                    JOptionPane.showMessageDialog(null, "El docente no existe ");
                } else {
                    tfnombredocente.setText(docente.getNombre());
                    List<Curso> lista = controlador.listarCursoPorDocente(docente);
                    if (lista != null) {
                        cargarComboCursos(lista);
                    }
                }
            }

        } catch (ExcepcionNegocio e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarAsignatura1ActionPerformed

    private void comboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCursoItemStateChanged
        // TODO add your handling code here:
        try {
            if (comboCurso.getSelectedIndex() == 0) {
                DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
                tabla.setRowCount(0);
                cargarComboEvaluacion(null);
            } else {
                String codigo = (String) comboCurso.getSelectedItem();
                if (codigo == null) {
                    return;
                }
                curso = controlador.buscarCurso(codigo);
                List<Evaluacion> evals = controlador.listaEvaluacionPorCurso(curso);
                cargarComboEvaluacion(evals);
            }
        } catch (ExcepcionNegocio e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception exc) {

            exc.printStackTrace();
        }

    }//GEN-LAST:event_comboCursoItemStateChanged

    private void combocalificacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocalificacionItemStateChanged
        try {
            if (combocalificacion.getSelectedIndex() != 0) {
                if (curso == null) {
                    JOptionPane.showMessageDialog(null, "Porfavor primero elija "
                            + "un curso");
                } else {
                    String notaEst = "N/C";
                    String nombre = (String) combocalificacion.getSelectedItem();
                    if (nombre == null) {
                        return;
                    }
                    Evaluacion eval = controlador.buscarEval(nombre, curso.getCodigo());
                    List<RegistroCurso> lista = controlador.listaRegistroCursoPorCurso(curso);
                    DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
                    tabla.setRowCount(0);
                    for (RegistroCurso rc : lista) {
                        Estudiante estudiante = rc.getEstudiante();
                        Nota nota = controlador.buscarNotaPorRegCurEval(rc, eval);
                        if (nota != null) {
                            notaEst = "" + nota.getValor();
                        }
                        tabla.addRow(new Object[]{estudiante.getCedula(), estudiante.getNombre(),
                            estudiante.getApellido(), notaEst});
                        notaEst = "N/C";
                    }
                }
            }
        } catch (ExcepcionNegocio e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception exc) {
            exc.printStackTrace();
        }

    }//GEN-LAST:event_combocalificacionItemStateChanged

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tabla = (DefaultTableModel) tablaCalificaicon.getModel();
            if (tabla.getRowCount() != 0) {
                if (combocalificacion.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Por favor elija la "
                            + "calificación");
                } else {
                    int c = tablaCalificaicon.getSelectedRow();
                    if (c > -1) {
                        String cedEst = (String) tabla.getValueAt(c, 0);
                        Estudiante e = controlador.buscarEstudiante(cedEst);
                        RegistroCurso rc = controlador.buscarRegistroCurso(curso, e);
                        String nombreEval = (String) combocalificacion.getSelectedItem();
                        Evaluacion eval = controlador.buscarEval(nombreEval, curso.getCodigo());
                        double nota = Double.parseDouble(
                                JOptionPane.showInputDialog("Ingrese la nota de la "
                                        + "calificación " + nombreEval + " para el/la estudiante "
                                        + e.getNombre()));
                        if (nota >= 0 && nota <= 5) {
                            controlador.crearNota(rc, nota, eval);
                            JOptionPane.showMessageDialog(null, "La nota ha sido "
                                    + "actualizada");
                            //Se actualiza la tabla...
                            String notaEst = "NC";
                            List<RegistroCurso> lista = controlador.listaRegistroCursoPorCurso(curso);
                            tabla.setRowCount(0);
                            for (RegistroCurso rec : lista) {
                                Estudiante est = rec.getEstudiante();
                                Nota nota1 = controlador.buscarNotaPorRegCurEval(rec, eval);
                                if (nota1 != null) {
                                    notaEst = "" + nota1.getValor();
                                }
                                tabla.addRow(new Object[]{est.getCedula(), est.getNombre(),
                                    est.getApellido(), notaEst});
                                notaEst = "NC";
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "La nota debe "
                                    + "estar entre 0 y 5 de calificación");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Porfavor seleccione un "
                                + "estudiante de la tabla");
                    }
                }
            }
        } catch (ExcepcionNegocio e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnCalificarActionPerformed
    public void cargarComboCursos(List<Curso> cursos) {
        comboCurso.removeAllItems();
        comboCurso.addItem("Seleccione un curso");
        for (int i = 0; i < cursos.size(); i++) {
            comboCurso.addItem(cursos.get(i).getCodigo());
        }
    }

    public void cargarComboEvaluacion(List<Evaluacion> lista) {
        combocalificacion.removeAllItems();
        if (lista != null) {
            combocalificacion.addItem("Seleccione una evaluación");
            for (int i = 0; i < lista.size(); i++) {
                combocalificacion.addItem(lista.get(i).getNombre());
            }
        } else {
            combocalificacion.addItem("No tiene evaluaciones");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura1;
    private javax.swing.JButton btnCalificar;
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JComboBox combocalificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCalificaicon;
    private javax.swing.JTextField tfceduladocente;
    private javax.swing.JTextField tfnombredocente;
    // End of variables declaration//GEN-END:variables
}
